// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: model/chat_send.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// POST /user.v1.ChatService/SendChatMessage
type SendChatMessageRequest struct {
	state                                protoimpl.MessageState `protogen:"open.v1"`
	UserId                               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChatRoomId                           string                 `protobuf:"bytes,2,opt,name=chat_room_id,json=chatRoomId,proto3" json:"chat_room_id,omitempty"`
	Content                              string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ImagePath                            string                 `protobuf:"bytes,4,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	UserUploadVideoId                    string                 `protobuf:"bytes,5,opt,name=user_upload_video_id,json=userUploadVideoId,proto3" json:"user_upload_video_id,omitempty"`
	ChatMessageId                        string                 `protobuf:"bytes,6,opt,name=chat_message_id,json=chatMessageId,proto3" json:"chat_message_id,omitempty"`
	ConfirmContainsForbiddenWordsWarning bool                   `protobuf:"varint,7,opt,name=confirm_contains_forbidden_words_warning,json=confirmContainsForbiddenWordsWarning,proto3" json:"confirm_contains_forbidden_words_warning,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *SendChatMessageRequest) Reset() {
	*x = SendChatMessageRequest{}
	mi := &file_model_chat_send_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageRequest) ProtoMessage() {}

func (x *SendChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_chat_send_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageRequest.ProtoReflect.Descriptor instead.
func (*SendChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_model_chat_send_proto_rawDescGZIP(), []int{0}
}

func (x *SendChatMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendChatMessageRequest) GetChatRoomId() string {
	if x != nil {
		return x.ChatRoomId
	}
	return ""
}

func (x *SendChatMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendChatMessageRequest) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *SendChatMessageRequest) GetUserUploadVideoId() string {
	if x != nil {
		return x.UserUploadVideoId
	}
	return ""
}

func (x *SendChatMessageRequest) GetChatMessageId() string {
	if x != nil {
		return x.ChatMessageId
	}
	return ""
}

func (x *SendChatMessageRequest) GetConfirmContainsForbiddenWordsWarning() bool {
	if x != nil {
		return x.ConfirmContainsForbiddenWordsWarning
	}
	return false
}

type SendChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatMessageResponse) Reset() {
	*x = SendChatMessageResponse{}
	mi := &file_model_chat_send_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageResponse) ProtoMessage() {}

func (x *SendChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_chat_send_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageResponse.ProtoReflect.Descriptor instead.
func (*SendChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_model_chat_send_proto_rawDescGZIP(), []int{1}
}

var File_model_chat_send_proto protoreflect.FileDescriptor

const file_model_chat_send_proto_rawDesc = "" +
	"\n" +
	"\x15model/chat_send.proto\x12\x05model\"\xbd\x02\n" +
	"\x16SendChatMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\fchat_room_id\x18\x02 \x01(\tR\n" +
	"chatRoomId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"image_path\x18\x04 \x01(\tR\timagePath\x12/\n" +
	"\x14user_upload_video_id\x18\x05 \x01(\tR\x11userUploadVideoId\x12&\n" +
	"\x0fchat_message_id\x18\x06 \x01(\tR\rchatMessageId\x12V\n" +
	"(confirm_contains_forbidden_words_warning\x18\a \x01(\bR$confirmContainsForbiddenWordsWarning\"\x19\n" +
	"\x17SendChatMessageResponseB\tZ\a./modelb\x06proto3"

var (
	file_model_chat_send_proto_rawDescOnce sync.Once
	file_model_chat_send_proto_rawDescData []byte
)

func file_model_chat_send_proto_rawDescGZIP() []byte {
	file_model_chat_send_proto_rawDescOnce.Do(func() {
		file_model_chat_send_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_chat_send_proto_rawDesc), len(file_model_chat_send_proto_rawDesc)))
	})
	return file_model_chat_send_proto_rawDescData
}

var file_model_chat_send_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_chat_send_proto_goTypes = []any{
	(*SendChatMessageRequest)(nil),  // 0: model.SendChatMessageRequest
	(*SendChatMessageResponse)(nil), // 1: model.SendChatMessageResponse
}
var file_model_chat_send_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_chat_send_proto_init() }
func file_model_chat_send_proto_init() {
	if File_model_chat_send_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_chat_send_proto_rawDesc), len(file_model_chat_send_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_chat_send_proto_goTypes,
		DependencyIndexes: file_model_chat_send_proto_depIdxs,
		MessageInfos:      file_model_chat_send_proto_msgTypes,
	}.Build()
	File_model_chat_send_proto = out.File
	file_model_chat_send_proto_goTypes = nil
	file_model_chat_send_proto_depIdxs = nil
}

