// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: external.proto

// 基于解包源码（/Users/bytedance/tools/replive/replive_src）里 Wire 生成代码反推。
// 目标：记录“我关注的声优/推し列表”对应的接口、入参和 resp 结构。

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OshiType int32

const (
	OshiType_OSHI_TYPE_UNSPECIFIED OshiType = 0
	OshiType_OSHI_TYPE_INDIVIDUAL  OshiType = 1
	OshiType_OSHI_TYPE_GROUP       OshiType = 2
)

// Enum value maps for OshiType.
var (
	OshiType_name = map[int32]string{
		0: "OSHI_TYPE_UNSPECIFIED",
		1: "OSHI_TYPE_INDIVIDUAL",
		2: "OSHI_TYPE_GROUP",
	}
	OshiType_value = map[string]int32{
		"OSHI_TYPE_UNSPECIFIED": 0,
		"OSHI_TYPE_INDIVIDUAL":  1,
		"OSHI_TYPE_GROUP":       2,
	}
)

func (x OshiType) Enum() *OshiType {
	p := new(OshiType)
	*p = x
	return p
}

func (x OshiType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OshiType) Descriptor() protoreflect.EnumDescriptor {
	return file_external_proto_enumTypes[0].Descriptor()
}

func (OshiType) Type() protoreflect.EnumType {
	return &file_external_proto_enumTypes[0]
}

func (x OshiType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OshiType.Descriptor instead.
func (OshiType) EnumDescriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{0}
}

type FollowTargetType int32

const (
	FollowTargetType_FOLLOW_TARGET_TYPE_UNSPECIFIED FollowTargetType = 0
	FollowTargetType_FOLLOW_TARGET_TYPE_USER        FollowTargetType = 1
	FollowTargetType_FOLLOW_TARGET_TYPE_OSHI        FollowTargetType = 2
)

// Enum value maps for FollowTargetType.
var (
	FollowTargetType_name = map[int32]string{
		0: "FOLLOW_TARGET_TYPE_UNSPECIFIED",
		1: "FOLLOW_TARGET_TYPE_USER",
		2: "FOLLOW_TARGET_TYPE_OSHI",
	}
	FollowTargetType_value = map[string]int32{
		"FOLLOW_TARGET_TYPE_UNSPECIFIED": 0,
		"FOLLOW_TARGET_TYPE_USER":        1,
		"FOLLOW_TARGET_TYPE_OSHI":        2,
	}
)

func (x FollowTargetType) Enum() *FollowTargetType {
	p := new(FollowTargetType)
	*p = x
	return p
}

func (x FollowTargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FollowTargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_external_proto_enumTypes[1].Descriptor()
}

func (FollowTargetType) Type() protoreflect.EnumType {
	return &file_external_proto_enumTypes[1]
}

func (x FollowTargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FollowTargetType.Descriptor instead.
func (FollowTargetType) EnumDescriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{1}
}

// POST https://api.replive.com/user.v1.UserService/ListMyOshis
type ListMyOshisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxPageSize   int64                  `protobuf:"varint,1,opt,name=max_page_size,json=maxPageSize,proto3" json:"max_page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOshisRequest) Reset() {
	*x = ListMyOshisRequest{}
	mi := &file_external_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOshisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOshisRequest) ProtoMessage() {}

func (x *ListMyOshisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOshisRequest.ProtoReflect.Descriptor instead.
func (*ListMyOshisRequest) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{0}
}

func (x *ListMyOshisRequest) GetMaxPageSize() int64 {
	if x != nil {
		return x.MaxPageSize
	}
	return 0
}

func (x *ListMyOshisRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListMyOshisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Oshis         []*ListMyOshisOshi     `protobuf:"bytes,1,rep,name=oshis,proto3" json:"oshis,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	MyOshisCount  int64                  `protobuf:"varint,3,opt,name=my_oshis_count,json=myOshisCount,proto3" json:"my_oshis_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOshisResponse) Reset() {
	*x = ListMyOshisResponse{}
	mi := &file_external_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOshisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOshisResponse) ProtoMessage() {}

func (x *ListMyOshisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOshisResponse.ProtoReflect.Descriptor instead.
func (*ListMyOshisResponse) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{1}
}

func (x *ListMyOshisResponse) GetOshis() []*ListMyOshisOshi {
	if x != nil {
		return x.Oshis
	}
	return nil
}

func (x *ListMyOshisResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListMyOshisResponse) GetMyOshisCount() int64 {
	if x != nil {
		return x.MyOshisCount
	}
	return 0
}

type ListMyOshisOshi struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OshiId             string                 `protobuf:"bytes,1,opt,name=oshi_id,json=oshiId,proto3" json:"oshi_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfileImageUrl    string                 `protobuf:"bytes,4,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	User               *OshiUser              `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	MembershipImageUrl string                 `protobuf:"bytes,7,opt,name=membership_image_url,json=membershipImageUrl,proto3" json:"membership_image_url,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListMyOshisOshi) Reset() {
	*x = ListMyOshisOshi{}
	mi := &file_external_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOshisOshi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOshisOshi) ProtoMessage() {}

func (x *ListMyOshisOshi) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOshisOshi.ProtoReflect.Descriptor instead.
func (*ListMyOshisOshi) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{2}
}

func (x *ListMyOshisOshi) GetOshiId() string {
	if x != nil {
		return x.OshiId
	}
	return ""
}

func (x *ListMyOshisOshi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListMyOshisOshi) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *ListMyOshisOshi) GetUser() *OshiUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ListMyOshisOshi) GetMembershipImageUrl() string {
	if x != nil {
		return x.MembershipImageUrl
	}
	return ""
}

type OshiUser struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	UserId                    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UniqueId                  string                 `protobuf:"bytes,2,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	DisplayName               string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ProfileImageUrl           string                 `protobuf:"bytes,4,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	ProfileBackgroundImageUrl string                 `protobuf:"bytes,13,opt,name=profile_background_image_url,json=profileBackgroundImageUrl,proto3" json:"profile_background_image_url,omitempty"`
	SmProfileImageUrl         string                 `protobuf:"bytes,18,opt,name=sm_profile_image_url,json=smProfileImageUrl,proto3" json:"sm_profile_image_url,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *OshiUser) Reset() {
	*x = OshiUser{}
	mi := &file_external_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OshiUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OshiUser) ProtoMessage() {}

func (x *OshiUser) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OshiUser.ProtoReflect.Descriptor instead.
func (*OshiUser) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{3}
}

func (x *OshiUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OshiUser) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *OshiUser) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *OshiUser) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *OshiUser) GetProfileBackgroundImageUrl() string {
	if x != nil {
		return x.ProfileBackgroundImageUrl
	}
	return ""
}

func (x *OshiUser) GetSmProfileImageUrl() string {
	if x != nil {
		return x.SmProfileImageUrl
	}
	return ""
}

type GetUserPrivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPrivateRequest) Reset() {
	*x = GetUserPrivateRequest{}
	mi := &file_external_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPrivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPrivateRequest) ProtoMessage() {}

func (x *GetUserPrivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPrivateRequest.ProtoReflect.Descriptor instead.
func (*GetUserPrivateRequest) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{4}
}

type GetUserPrivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserPrivate           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPrivateResponse) Reset() {
	*x = GetUserPrivateResponse{}
	mi := &file_external_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPrivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPrivateResponse) ProtoMessage() {}

func (x *GetUserPrivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPrivateResponse.ProtoReflect.Descriptor instead.
func (*GetUserPrivateResponse) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserPrivateResponse) GetUser() *UserPrivate {
	if x != nil {
		return x.User
	}
	return nil
}

// POST https://api.replive.com/user.v1.UserService/ListFollowings
type ListFollowingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	MaxPageSize   int64                  `protobuf:"varint,3,opt,name=max_page_size,json=maxPageSize,proto3" json:"max_page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Type          FollowTargetType       `protobuf:"varint,5,opt,name=type,proto3,enum=model.FollowTargetType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingsRequest) Reset() {
	*x = ListFollowingsRequest{}
	mi := &file_external_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingsRequest) ProtoMessage() {}

func (x *ListFollowingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingsRequest.ProtoReflect.Descriptor instead.
func (*ListFollowingsRequest) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{6}
}

func (x *ListFollowingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListFollowingsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListFollowingsRequest) GetMaxPageSize() int64 {
	if x != nil {
		return x.MaxPageSize
	}
	return 0
}

func (x *ListFollowingsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListFollowingsRequest) GetType() FollowTargetType {
	if x != nil {
		return x.Type
	}
	return FollowTargetType_FOLLOW_TARGET_TYPE_UNSPECIFIED
}

type ListFollowingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowTargets []*FollowTarget        `protobuf:"bytes,1,rep,name=follow_targets,json=followTargets,proto3" json:"follow_targets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingsResponse) Reset() {
	*x = ListFollowingsResponse{}
	mi := &file_external_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingsResponse) ProtoMessage() {}

func (x *ListFollowingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingsResponse.ProtoReflect.Descriptor instead.
func (*ListFollowingsResponse) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{7}
}

func (x *ListFollowingsResponse) GetFollowTargets() []*FollowTarget {
	if x != nil {
		return x.FollowTargets
	}
	return nil
}

func (x *ListFollowingsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type FollowTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FollowTargetType       `protobuf:"varint,1,opt,name=type,proto3,enum=model.FollowTargetType" json:"type,omitempty"`
	User          *OshiUser              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Oshi          *ListMyOshisOshi       `protobuf:"bytes,3,opt,name=oshi,proto3" json:"oshi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowTarget) Reset() {
	*x = FollowTarget{}
	mi := &file_external_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowTarget) ProtoMessage() {}

func (x *FollowTarget) ProtoReflect() protoreflect.Message {
	mi := &file_external_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowTarget.ProtoReflect.Descriptor instead.
func (*FollowTarget) Descriptor() ([]byte, []int) {
	return file_external_proto_rawDescGZIP(), []int{8}
}

func (x *FollowTarget) GetType() FollowTargetType {
	if x != nil {
		return x.Type
	}
	return FollowTargetType_FOLLOW_TARGET_TYPE_UNSPECIFIED
}

func (x *FollowTarget) GetUser() *OshiUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *FollowTarget) GetOshi() *ListMyOshisOshi {
	if x != nil {
		return x.Oshi
	}
	return nil
}

var File_external_proto protoreflect.FileDescriptor

const file_external_proto_rawDesc = "" +
	"\n" +
	"\x0eexternal.proto\x12\x05model\x1a\n" +
	"http.proto\"W\n" +
	"\x12ListMyOshisRequest\x12\"\n" +
	"\rmax_page_size\x18\x01 \x01(\x03R\vmaxPageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x91\x01\n" +
	"\x13ListMyOshisResponse\x12,\n" +
	"\x05oshis\x18\x01 \x03(\v2\x16.model.ListMyOshisOshiR\x05oshis\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12$\n" +
	"\x0emy_oshis_count\x18\x03 \x01(\x03R\fmyOshisCount\"\xdf\x01\n" +
	"\x0fListMyOshisOshi\x12\x17\n" +
	"\aoshi_id\x18\x01 \x01(\tR\x06oshiId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x11profile_image_url\x18\x04 \x01(\tR\x0fprofileImageUrl\x12#\n" +
	"\x04user\x18\x05 \x01(\v2\x0f.model.OshiUserR\x04user\x120\n" +
	"\x14membership_image_url\x18\a \x01(\tR\x12membershipImageUrlJ\x04\b\x03\x10\x04J\x04\b\x06\x10\aJ\x04\b\b\x10\tJ\x04\bd\x10eJ\x04\be\x10f\"\x93\x02\n" +
	"\bOshiUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tunique_id\x18\x02 \x01(\tR\buniqueId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12*\n" +
	"\x11profile_image_url\x18\x04 \x01(\tR\x0fprofileImageUrl\x12?\n" +
	"\x1cprofile_background_image_url\x18\r \x01(\tR\x19profileBackgroundImageUrl\x12/\n" +
	"\x14sm_profile_image_url\x18\x12 \x01(\tR\x11smProfileImageUrlJ\x04\b\x05\x10\rJ\x04\b\x0e\x10\x12J\x04\b\x13\x10\x1a\"\x17\n" +
	"\x15GetUserPrivateRequest\"@\n" +
	"\x16GetUserPrivateResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.model.UserPrivateR\x04user\"\xb8\x01\n" +
	"\x15ListFollowingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\"\n" +
	"\rmax_page_size\x18\x03 \x01(\x03R\vmaxPageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12+\n" +
	"\x04type\x18\x05 \x01(\x0e2\x17.model.FollowTargetTypeR\x04type\"|\n" +
	"\x16ListFollowingsResponse\x12:\n" +
	"\x0efollow_targets\x18\x01 \x03(\v2\x13.model.FollowTargetR\rfollowTargets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x8c\x01\n" +
	"\fFollowTarget\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.model.FollowTargetTypeR\x04type\x12#\n" +
	"\x04user\x18\x02 \x01(\v2\x0f.model.OshiUserR\x04user\x12*\n" +
	"\x04oshi\x18\x03 \x01(\v2\x16.model.ListMyOshisOshiR\x04oshi*T\n" +
	"\bOshiType\x12\x19\n" +
	"\x15OSHI_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OSHI_TYPE_INDIVIDUAL\x10\x01\x12\x13\n" +
	"\x0fOSHI_TYPE_GROUP\x10\x02*p\n" +
	"\x10FollowTargetType\x12\"\n" +
	"\x1eFOLLOW_TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FOLLOW_TARGET_TYPE_USER\x10\x01\x12\x1b\n" +
	"\x17FOLLOW_TARGET_TYPE_OSHI\x10\x02B\tZ\a./modelb\x06proto3"

var (
	file_external_proto_rawDescOnce sync.Once
	file_external_proto_rawDescData []byte
)

func file_external_proto_rawDescGZIP() []byte {
	file_external_proto_rawDescOnce.Do(func() {
		file_external_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_external_proto_rawDesc), len(file_external_proto_rawDesc)))
	})
	return file_external_proto_rawDescData
}

var file_external_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_external_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_external_proto_goTypes = []any{
	(OshiType)(0),                  // 0: model.OshiType
	(FollowTargetType)(0),          // 1: model.FollowTargetType
	(*ListMyOshisRequest)(nil),     // 2: model.ListMyOshisRequest
	(*ListMyOshisResponse)(nil),    // 3: model.ListMyOshisResponse
	(*ListMyOshisOshi)(nil),        // 4: model.ListMyOshisOshi
	(*OshiUser)(nil),               // 5: model.OshiUser
	(*GetUserPrivateRequest)(nil),  // 6: model.GetUserPrivateRequest
	(*GetUserPrivateResponse)(nil), // 7: model.GetUserPrivateResponse
	(*ListFollowingsRequest)(nil),  // 8: model.ListFollowingsRequest
	(*ListFollowingsResponse)(nil), // 9: model.ListFollowingsResponse
	(*FollowTarget)(nil),           // 10: model.FollowTarget
	(*UserPrivate)(nil),            // 11: model.UserPrivate
}
var file_external_proto_depIdxs = []int32{
	4,  // 0: model.ListMyOshisResponse.oshis:type_name -> model.ListMyOshisOshi
	5,  // 1: model.ListMyOshisOshi.user:type_name -> model.OshiUser
	11, // 2: model.GetUserPrivateResponse.user:type_name -> model.UserPrivate
	1,  // 3: model.ListFollowingsRequest.type:type_name -> model.FollowTargetType
	10, // 4: model.ListFollowingsResponse.follow_targets:type_name -> model.FollowTarget
	1,  // 5: model.FollowTarget.type:type_name -> model.FollowTargetType
	5,  // 6: model.FollowTarget.user:type_name -> model.OshiUser
	4,  // 7: model.FollowTarget.oshi:type_name -> model.ListMyOshisOshi
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_external_proto_init() }
func file_external_proto_init() {
	if File_external_proto != nil {
		return
	}
	file_http_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_external_proto_rawDesc), len(file_external_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_external_proto_goTypes,
		DependencyIndexes: file_external_proto_depIdxs,
		EnumInfos:         file_external_proto_enumTypes,
		MessageInfos:      file_external_proto_msgTypes,
	}.Build()
	File_external_proto = out.File
	file_external_proto_goTypes = nil
	file_external_proto_depIdxs = nil
}
