package service

import (
	"fmt"
	"os"
	"path/filepath"
	"replive/dal"
	"time"

	"github.com/cloudwego/hertz/pkg/common/hlog"
)

const (
	fandomImageMessageType int32 = 2
	fandomVideoMessageType int32 = 3
)

// BackfillChatMediaPaths reconnects archived Fandom media with rows created
// before local media paths were persisted. It only accepts the exact filename
// generated by the existing downloader and never scans arbitrary directories.
func BackfillChatMediaPaths() error {
	imageCount, err := backfillChatMediaPath(fandomImageMessageType, "image_path", "image_url")
	if err != nil {
		return err
	}
	videoCount, err := backfillChatMediaPath(fandomVideoMessageType, "video_path", "video_url")
	if err != nil {
		return err
	}
	if imageCount+videoCount > 0 {
		hlog.Infof("backfilled local Fandom media paths: images=%d videos=%d", imageCount, videoCount)
	}
	return nil
}

func backfillChatMediaPath(msgType int32, pathColumn, urlColumn string) (int, error) {
	messages := make([]dal.ChatMessage, 0)
	if err := dal.ReadDB().
		Where("msg_type = ? AND TRIM("+pathColumn+") = '' AND TRIM("+urlColumn+") <> ''", msgType).
		Find(&messages).Error; err != nil {
		return 0, err
	}

	updated := 0
	for _, message := range messages {
		candidate, ok := expectedArchivedMediaPath(message)
		if !ok {
			continue
		}
		info, err := os.Stat(candidate)
		if err != nil || !info.Mode().IsRegular() {
			continue
		}
		result := dal.ReadDB().Model(&dal.ChatMessage{}).
			Where("id = ? AND TRIM("+pathColumn+") = ''", message.Id).
			Update(pathColumn, candidate)
		if result.Error != nil {
			return updated, result.Error
		}
		updated += int(result.RowsAffected)
	}
	return updated, nil
}

func expectedArchivedMediaPath(message dal.ChatMessage) (string, bool) {
	if message.SendTime <= 0 || message.ChatMessageId == "" || message.DisplayName == "" {
		return "", false
	}
	mediaTime := time.Unix(message.SendTime, 0)
	switch message.MsgType {
	case fandomImageMessageType:
		if message.ImageUrl == "" {
			return "", false
		}
		name, dir, err := getImgFileName(message.ImageUrl, mediaTime, message.ChatMessageId)
		if err != nil {
			return "", false
		}
		return filepath.Join(getMediaPath(message.DisplayName), filepath.FromSlash(dir), name), true
	case fandomVideoMessageType:
		if message.VideoUrl == "" {
			return "", false
		}
		name := fmt.Sprintf("%s_%s.mp4", mediaTime.Format("2006-01-02"), message.ChatMessageId)
		return filepath.Join(getMediaPath(message.DisplayName), fmt.Sprintf("%d", mediaTime.Year()), fmt.Sprintf("%d", mediaTime.Month()), name), true
	default:
		return "", false
	}
}
