package service

import (
	"fmt"
	"path/filepath"
	"replive/dal"
	"time"

	"github.com/cloudwego/hertz/pkg/common/hlog"
	"gorm.io/gorm"
)

const (
	fandomImageMessageType int32 = 2
	fandomVideoMessageType int32 = 3
)

type chatMediaRepairSummary struct {
	relinked   int
	downloaded int
	skipped    int
	failed     int
}

// BackfillChatMediaPaths reconnects archived Fandom media with rows created
// before local media paths were persisted and repairs rows whose local file
// was deleted. It only accepts the exact filename generated by the existing
// downloader and never scans arbitrary directories.
func BackfillChatMediaPaths() error {
	imageSummary, err := repairChatMediaPath(fandomImageMessageType, "image_path", "image_url")
	if err != nil {
		return err
	}
	videoSummary, err := repairChatMediaPath(fandomVideoMessageType, "video_path", "video_url")
	if err != nil {
		return err
	}

	relinked := imageSummary.relinked + videoSummary.relinked
	downloaded := imageSummary.downloaded + videoSummary.downloaded
	skipped := imageSummary.skipped + videoSummary.skipped
	failed := imageSummary.failed + videoSummary.failed
	if relinked > 0 {
		hlog.Infof("backfilled local Fandom media paths: images=%d videos=%d", imageSummary.relinked, videoSummary.relinked)
	}
	if downloaded > 0 || failed > 0 {
		hlog.Infof("chat media repair: downloaded=%d skipped=%d failed=%d", downloaded, skipped, failed)
	}
	return nil
}

func repairChatMediaPath(msgType int32, pathColumn, urlColumn string) (chatMediaRepairSummary, error) {
	summary := chatMediaRepairSummary{}
	messages := make([]dal.ChatMessage, 0)
	if err := dal.ReadDB().
		Where("msg_type = ? AND TRIM("+urlColumn+") <> ''", msgType).
		Find(&messages).Error; err != nil {
		return summary, err
	}

	for _, message := range messages {
		candidate, ok := expectedArchivedMediaPath(message)
		if !ok {
			continue
		}
		storedPath := message.ImagePath
		if msgType == fandomVideoMessageType {
			storedPath = message.VideoPath
		}
		if mediaFileExists(storedPath) {
			continue
		}

		if mediaFileExists(candidate) {
			if err := updateChatMediaPath(message.Id, pathColumn, candidate); err != nil {
				return summary, err
			}
			summary.relinked++
			continue
		}

		path, result, err := downloadArchivedChatMedia(message, candidate)
		if err != nil {
			summary.failed++
			hlog.Warnf("chat media repair failed, msgId=%s: %v", message.ChatMessageId, err)
			continue
		}
		if err := updateChatMediaPath(message.Id, pathColumn, path); err != nil {
			return summary, err
		}
		if result == MediaSkipped {
			summary.skipped++
		} else {
			summary.downloaded++
		}
	}
	return summary, nil
}

func updateChatMediaPath(id int64, pathColumn, path string) error {
	return dal.WithWriteDB(func(db *gorm.DB) error {
		return db.Model(&dal.ChatMessage{}).
			Where("id = ?", id).
			Update(pathColumn, path).Error
	})
}

func downloadArchivedChatMedia(message dal.ChatMessage, candidate string) (string, MediaResult, error) {
	mediaTime := time.Unix(message.SendTime, 0)
	switch message.MsgType {
	case fandomImageMessageType:
		return DownloadImageWithResult(message.ImageUrl, mediaTime, getMediaPath(message.DisplayName), message.ChatMessageId)
	case fandomVideoMessageType:
		return DownloadVideoWithResult(message.VideoUrl, mediaTime, getMediaPath(message.DisplayName), message.ChatMessageId)
	default:
		return candidate, MediaFailed, fmt.Errorf("unsupported message type: %d", message.MsgType)
	}
}

func expectedArchivedMediaPath(message dal.ChatMessage) (string, bool) {
	if message.SendTime <= 0 || message.ChatMessageId == "" || message.DisplayName == "" {
		return "", false
	}
	mediaTime := time.Unix(message.SendTime, 0)
	switch message.MsgType {
	case fandomImageMessageType:
		if message.ImageUrl == "" {
			return "", false
		}
		name, dir, err := getImgFileName(message.ImageUrl, mediaTime, message.ChatMessageId)
		if err != nil {
			return "", false
		}
		return filepath.Join(getMediaPath(message.DisplayName), filepath.FromSlash(dir), name), true
	case fandomVideoMessageType:
		if message.VideoUrl == "" {
			return "", false
		}
		name := fmt.Sprintf("%s_%s.mp4", mediaTime.Format("2006-01-02"), message.ChatMessageId)
		return filepath.Join(getMediaPath(message.DisplayName), fmt.Sprintf("%d", mediaTime.Year()), fmt.Sprintf("%d", mediaTime.Month()), name), true
	default:
		return "", false
	}
}
